version: "3.8"

services:
  mysqldb:
    
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_db
    networks:
      - springboot-mysql-net  

  springboot-restful-webservices:
    
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      - mysqldb  
    networks:
      - springboot-mysql-net  
    restart: on-failure

networks:
  springboot-mysql-net: